name: Flutter CI

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    - name: Install dependencies
      run: flutter pub get

    - name: Install barcode_scan2 and http packages
      run: flutter pub add barcode_scan2 http

    - name: Run tests
      run: flutter test

    - name: Build app for Android
      run: flutter build apk
