name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Run integration tests
      run: flutter drive --target=test_driver/app.dart

    - name: Build app for Android
      run: flutter build apk

    - name: Build app for iOS
      run: flutter build ios

    - name: Build app for web
      run: flutter build web

    - name: Build app for Windows
      run: flutter build windows

    - name: Build app for macOS
      run: flutter build macos

    - name: Build app for Linux
      run: flutter build linux
